//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProjelerim
    {
        public int id { get; set; }
        public string ProjeName { get; set; }
        public string ProjeAciklama { get; set; }
        public string ProjeResim1 { get; set; }
        public string ProjeResim2 { get; set; }
        public string ProjeResim3 { get; set; }
    }
}
